-- MySQL Script generated by MySQL Workbench
-- Wed Dec 23 23:55:34 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`projekt_kregielnia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`projekt_kregielnia` (
  `id_kregielni` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `adres` VARCHAR(20) NOT NULL,
  `kod_pocztowy` VARCHAR(8) NOT NULL,
  `nr_telefonu` VARCHAR(9) NOT NULL,
  `godz_otwarcia` VARCHAR(20) NOT NULL,
  `godz_zamkniecia` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_kregielni`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`projekt_pracownicy`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`projekt_pracownicy` (
  `id_pracownika` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `imie` VARCHAR(10) NOT NULL,
  `nazwisko` VARCHAR(20) NOT NULL,
  `adres_zamieszkania` VARCHAR(20) NOT NULL,
  `data_ur` DATE NOT NULL,
  `nr_telefonu` VARCHAR(9) NOT NULL,
  `adres_mailowy` VARCHAR(30) NOT NULL,
  `data_dodania` DATETIME NOT NULL,
  `id_kregielni` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id_pracownika`),
  INDEX `fk_projekt_pracownicy_projekt_kregielnia1_idx` (`id_kregielni` ASC) VISIBLE,
  CONSTRAINT `fk_projekt_pracownicy_projekt_kregielnia1`
    FOREIGN KEY (`id_kregielni`)
    REFERENCES `mydb`.`projekt_kregielnia` (`id_kregielni`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`projekt_klienci`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`projekt_klienci` (
  `id_klienta` INT NOT NULL AUTO_INCREMENT,
  `imie` VARCHAR(10) NOT NULL,
  `nazwisko` VARCHAR(20) NOT NULL,
  `nr_telefonu` VARCHAR(13) NOT NULL,
  `rozmiar_buta` VARCHAR(2) NOT NULL,
  `id_kregielni` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id_klienta`),
  INDEX `fk_projekt_klienci_projekt_kregielnia1_idx` (`id_kregielni` ASC) VISIBLE,
  CONSTRAINT `fk_projekt_klienci_projekt_kregielnia1`
    FOREIGN KEY (`id_kregielni`)
    REFERENCES `mydb`.`projekt_kregielnia` (`id_kregielni`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`projekt_rezerwacje`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`projekt_rezerwacje` (
  `id_rezerwacji` INT NOT NULL AUTO_INCREMENT,
  `data_od` DATE NOT NULL,
  `data_do` DATE NOT NULL,
  `godzina_od` TIME NOT NULL,
  `godzina_do` TIME NOT NULL,
  `tor` ENUM('1', '2', '3', '4') NOT NULL,
  `stolik` ENUM('1', '2', '3', '4', '5', '6', '7', '8') NOT NULL,
  `liczba_os` VARCHAR(1) NOT NULL,
  `id_klienta` INT NOT NULL,
  `id_pracownika` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id_rezerwacji`),
  INDEX `fk_projekt_rezerwacje_projekt_klienci1_idx` (`id_klienta` ASC) VISIBLE,
  INDEX `fk_projekt_rezerwacje_projekt_pracownicy1_idx` (`id_pracownika` ASC) VISIBLE,
  CONSTRAINT `fk_projekt_rezerwacje_projekt_klienci1`
    FOREIGN KEY (`id_klienta`)
    REFERENCES `mydb`.`projekt_klienci` (`id_klienta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_projekt_rezerwacje_projekt_pracownicy1`
    FOREIGN KEY (`id_pracownika`)
    REFERENCES `mydb`.`projekt_pracownicy` (`id_pracownika`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`projekt_platnosci`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`projekt_platnosci` (
  `id_platnosci` INT NOT NULL AUTO_INCREMENT,
  `gotowka` VARCHAR(1) NULL DEFAULT 0,
  `karta_kredytowa` VARCHAR(1) NULL DEFAULT 0,
  `karta_zblizeniowa` VARCHAR(1) NULL DEFAULT 0,
  `BLIK` VARCHAR(1) NULL DEFAULT 0,
  `przelew` VARCHAR(1) NULL DEFAULT 0,
  `id_rezerwacji` INT NOT NULL,
  `id_klienta` INT NOT NULL,
  PRIMARY KEY (`id_platnosci`),
  INDEX `fk_projekt_platnosci_projekt_rezerwacje1_idx` (`id_rezerwacji` ASC) VISIBLE,
  INDEX `fk_projekt_platnosci_projekt_klienci1_idx` (`id_klienta` ASC) VISIBLE,
  CONSTRAINT `fk_projekt_platnosci_projekt_rezerwacje1`
    FOREIGN KEY (`id_rezerwacji`)
    REFERENCES `mydb`.`projekt_rezerwacje` (`id_rezerwacji`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_projekt_platnosci_projekt_klienci1`
    FOREIGN KEY (`id_klienta`)
    REFERENCES `mydb`.`projekt_klienci` (`id_klienta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`projekt_oferty_promocyjne`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`projekt_oferty_promocyjne` (
  `id_oferty` INT NOT NULL AUTO_INCREMENT,
  `urodziny` VARCHAR(1) NULL DEFAULT 0,
  `wieczor_kawalerski` VARCHAR(1) NULL DEFAULT 0,
  `wieczor_panienski` VARCHAR(1) NULL DEFAULT 0,
  `18tka` VARCHAR(1) NULL DEFAULT 0,
  `studenckie_piatki` VARCHAR(1) NULL DEFAULT 0,
  `id_rezerwacji` INT NOT NULL,
  PRIMARY KEY (`id_oferty`),
  INDEX `fk_projekt_oferty_promocyjne_projekt_rezerwacje1_idx` (`id_rezerwacji` ASC) VISIBLE,
  CONSTRAINT `fk_projekt_oferty_promocyjne_projekt_rezerwacje1`
    FOREIGN KEY (`id_rezerwacji`)
    REFERENCES `mydb`.`projekt_rezerwacje` (`id_rezerwacji`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`projekt_warunki_zatrudnienia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`projekt_warunki_zatrudnienia` (
  `idWarunki_zatrudnienia` INT NOT NULL AUTO_INCREMENT,
  `stawka` VARCHAR(7) NOT NULL,
  `liczba_godz` VARCHAR(4) NOT NULL,
  `rodz_umowy` ENUM('umowa_zlecenie', 'umowa_o_prace') NOT NULL,
  `stanowisko` ENUM('sprzedawca', 'sprzataczka', 'ochroniarz', 'konserwator', 'specjalista_ds_zakupow', 'kierownik') NOT NULL,
  `wyksztalcenie` ENUM('gimnazjalne', 'zasadnicze_zawodowe', 'srednie', 'policealne', 'wyzsze_zawodowe', 'wyzsze_magisterskie', 'wyzsze_magisterskie_inzynierskie') NOT NULL,
  `data_mod` DATETIME NOT NULL,
  `pop_stawka` VARCHAR(7) NOT NULL,
  `id_pracownika` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`idWarunki_zatrudnienia`),
  INDEX `fk_projekt_warunki_zatrudnienia_projekt_pracownicy1_idx` (`id_pracownika` ASC) VISIBLE,
  CONSTRAINT `fk_projekt_warunki_zatrudnienia_projekt_pracownicy1`
    FOREIGN KEY (`id_pracownika`)
    REFERENCES `mydb`.`projekt_pracownicy` (`id_pracownika`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`projekt_rabaty`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`projekt_rabaty` (
  `id_rabatu` INT NOT NULL,
  `kod_promocyjny` VARCHAR(45) NULL,
  `karta_znizkowa` VARCHAR(45) NULL,
  `id_platnosci` INT NOT NULL,
  PRIMARY KEY (`id_rabatu`),
  INDEX `fk_projekt_rabaty_projekt_platnosci1_idx` (`id_platnosci` ASC) VISIBLE,
  CONSTRAINT `fk_projekt_rabaty_projekt_platnosci1`
    FOREIGN KEY (`id_platnosci`)
    REFERENCES `mydb`.`projekt_platnosci` (`id_platnosci`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

USE `mydb`;

DELIMITER $$
USE `mydb`$$
CREATE DEFINER = CURRENT_USER TRIGGER `mydb`.`projekt_pracownicy_BEFORE_INSERT` BEFORE INSERT ON `projekt_pracownicy` FOR EACH ROW
BEGIN
SET NEW.data_dodania = now();
END$$

USE `mydb`$$
CREATE DEFINER = CURRENT_USER TRIGGER `mydb`.`projekt_warunki_zatrudnienia_BEFORE_UPDATE` BEFORE UPDATE ON `projekt_warunki_zatrudnienia` FOR EACH ROW
BEGIN
SET NEW.data_mod = now();

IF NEW.stawka!=OLD.stawka THEN
SET NEW.pop_stawka = OLD.stawka;
END IF;

END$$


DELIMITER ;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

DELIMITER $$
CREATE PROCEDURE premia(IN id int)
BEGIN
Update projekt_warunki_zatrudnienia SET stawka = 1.3;
END$$